include:
  template: Terraform-Module.gitlab-ci.yml

default:
  image:
    name: lwith/gitlab-devops:latest

stages:
  - validate
  - deploy
  - test

variables:
  TERRAFORM_MODULE_SYSTEM: $CI_COMMIT_BRANCH
